# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NetClus
                                 A QGIS plugin
 This plugin make cluster nalysis base on network layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-14
        copyright            : (C) 2025 by Surya Hafizh
        email                : suryahafizh979@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NetClus class from file NetClus.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Net_clus import NetClus
    return NetClus(iface)
